### PR TITLE
switched to circleci

### PR DESCRIPTION
**Pull request by sjha2048**
references: #162

### CODE REVIEW

**Comment by sjha2048** [comment]
can you review this  @hexedpackets please?

**Comment by hexedpackets** [comment]
This looks good, thanks! Only thing missing is ensuring it only runs on commits to `master` - mind adding that in?

**Comment by sjha2048** [comment]
Sure

**Comment by sjha2048** [comment]
please have a look at it once :)

**Review by hexedpackets — APPROVED** [review]

**Pull request merged**
