### PR TITLE
[opencensus] Sanitize metric and label/tag names.

### PR DESCRIPTION
**Pull request by hnjslater**
Also decrease maxViews to 500 as this is the default limit in
Stackdriver.

### CODE REVIEW

**Comment by gurshafriri** [comment]
👋 is this concerning a potential attack vector, or just a "best practice" change?

**Comment by hnjslater** [comment]
Neither, Currently some of the metrics we're passing through have tags/labels with hyphens in them causing the labels to be dropped during Stackdriver ingestion.

**Review by sjoeboo — APPROVED** [review]

**Comment by hnjslater** [comment]
Ugh, I just noticed, I missed actually updating the tag name when recording a timepoint, I'll send another commit.

UPDATE: Pushed, see https://github.com/spotify/ffwd/pull/197/commits/7be608c0ff8dc0fd34504c102f8ede8a5248fa66

**Review by malish8632 — COMMENTED** [review]
LGTM
For some reason it shows that your branch is not up today with master.
Could you rebase and update your branch?

**Comment by hnjslater** [comment]
I'm sorry to say my git and github knowledge is very rusty. Is that better?

**Review by malish8632 — APPROVED** [review]
Much better.
Thanks.

**Pull request merged**
